<?php

use CRM_SamlAuth_ExtensionUtil as E;

/**
 * Every setting here is both UI-editable and env-overridable via the
 * CIVICRM_SAML_AUTH_* environment variable listed in `global_name`.
 *
 * When the env var is set, CiviCRM's SettingsBag::getMandatory() returns
 * non-NULL for that key and the UI renders the field read-only (secrets
 * are also masked) — see Civi\SamlAuth\Subscriber\SettingsFormSubscriber.
 */
return [
  'saml_auth_mode' => [
    'name' => 'saml_auth_mode',
    'type' => 'String',
    'default' => 'disabled',
    'html_type' => 'select',
    'title' => E::ts('SAML Login Mode'),
    'description' => E::ts('disabled = password only; optional = password + SSO button; required = SSO only (password form hidden and the login page auto-redirects to the IdP).'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_MODE',
    'pseudoconstant' => [
      'callback' => ['CRM_SamlAuth_Form_Settings', 'getModeOptions'],
    ],
  ],
  'saml_auth_debug' => [
    'name' => 'saml_auth_debug',
    'type' => 'Boolean',
    'default' => FALSE,
    'html_type' => 'checkbox',
    'title' => E::ts('Debug Mode'),
    'description' => E::ts('Enable detailed SAML debugging to the CiviCRM log.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_DEBUG',
  ],
  'saml_auth_idp_entity_id' => [
    'name' => 'saml_auth_idp_entity_id',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('IdP Entity ID'),
    'description' => E::ts('The Entity ID (Issuer) of your SAML Identity Provider.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_IDP_ENTITY_ID',
  ],
  'saml_auth_idp_sso_url' => [
    'name' => 'saml_auth_idp_sso_url',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('IdP SSO URL'),
    'description' => E::ts('The Single Sign-On URL of your Identity Provider.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_IDP_SSO_URL',
  ],
  'saml_auth_idp_x509_cert' => [
    'name' => 'saml_auth_idp_x509_cert',
    'type' => 'Text',
    'default' => '',
    'html_type' => 'textarea',
    'title' => E::ts('IdP X.509 Certificate'),
    'description' => E::ts('The public X.509 certificate of your Identity Provider. Paste the body without BEGIN/END lines.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_IDP_X509_CERT',
  ],
  'saml_auth_sp_entity_id' => [
    'name' => 'saml_auth_sp_entity_id',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('SP Entity ID'),
    'description' => E::ts('Your CiviCRM Entity ID (defaults to this site\'s base URL when empty).'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_SP_ENTITY_ID',
  ],
  'saml_auth_sp_x509_cert' => [
    'name' => 'saml_auth_sp_x509_cert',
    'type' => 'Text',
    'default' => '',
    'html_type' => 'textarea',
    'title' => E::ts('SP X.509 Certificate'),
    'description' => E::ts('Public SP certificate used when signing AuthnRequests or publishing SP metadata. Paste body only, no BEGIN/END lines.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_SP_X509_CERT',
  ],
  'saml_auth_sp_private_key' => [
    'name' => 'saml_auth_sp_private_key',
    'type' => 'Text',
    'default' => '',
    'html_type' => 'textarea',
    'title' => E::ts('SP Private Key'),
    'description' => E::ts('SP private key used to sign AuthnRequests. Strongly recommended to set via the CIVICRM_SAML_AUTH_SP_PRIVATE_KEY environment variable rather than in the DB.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_SP_PRIVATE_KEY',
  ],
  'saml_auth_sign_requests' => [
    'name' => 'saml_auth_sign_requests',
    'type' => 'Boolean',
    'default' => FALSE,
    'html_type' => 'checkbox',
    'title' => E::ts('Sign AuthnRequests'),
    'description' => E::ts('Sign outbound AuthnRequests with the SP private key. Requires SP certificate and private key to be configured.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_SIGN_REQUESTS',
  ],
  'saml_auth_match_field' => [
    'name' => 'saml_auth_match_field',
    'type' => 'String',
    'default' => 'email',
    'html_type' => 'select',
    'title' => E::ts('User Match Field'),
    'description' => E::ts('Which CiviCRM User field to match the incoming SAML identity against.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_MATCH_FIELD',
    'pseudoconstant' => [
      'callback' => ['CRM_SamlAuth_Form_Settings', 'getMatchFieldOptions'],
    ],
  ],
  'saml_auth_provisioning_enabled' => [
    'name' => 'saml_auth_provisioning_enabled',
    'type' => 'Boolean',
    'default' => TRUE,
    'html_type' => 'checkbox',
    'title' => E::ts('Auto-provision Users'),
    'description' => E::ts('When enabled, an unknown SAML identity results in a new CiviCRM User/Contact being created on first login.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_PROVISIONING_ENABLED',
  ],
  'saml_auth_attr_username' => [
    'name' => 'saml_auth_attr_username',
    'type' => 'String',
    'default' => 'username',
    'html_type' => 'text',
    'title' => E::ts('SAML attribute: username'),
    'description' => E::ts('Name of the SAML attribute that carries the username. Leave blank to skip username when provisioning / fall back to NameID.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_ATTR_USERNAME',
  ],
  'saml_auth_attr_email' => [
    'name' => 'saml_auth_attr_email',
    'type' => 'String',
    'default' => 'email',
    'html_type' => 'text',
    'title' => E::ts('SAML attribute: email'),
    'description' => E::ts('Name of the SAML attribute that carries the email address. Leave blank to fall back to NameID when match field is email.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_ATTR_EMAIL',
  ],
  'saml_auth_attr_first_name' => [
    'name' => 'saml_auth_attr_first_name',
    'type' => 'String',
    'default' => 'firstName',
    'html_type' => 'text',
    'title' => E::ts('SAML attribute: first name'),
    'description' => E::ts('Leave blank to skip first name.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_ATTR_FIRST_NAME',
  ],
  'saml_auth_attr_last_name' => [
    'name' => 'saml_auth_attr_last_name',
    'type' => 'String',
    'default' => 'lastName',
    'html_type' => 'text',
    'title' => E::ts('SAML attribute: last name'),
    'description' => E::ts('Leave blank to skip last name.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_ATTR_LAST_NAME',
  ],
  'saml_auth_attr_roles' => [
    'name' => 'saml_auth_attr_roles',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('SAML attribute: roles'),
    'description' => E::ts('Name of the SAML attribute whose values map to CiviCRM Role names. Leave blank to skip role sync. Role names from the IdP must match CiviCRM role names exactly.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_ATTR_ROLES',
  ],
  'saml_auth_relaystate_allowlist' => [
    'name' => 'saml_auth_relaystate_allowlist',
    'type' => 'Text',
    'default' => '',
    'html_type' => 'textarea',
    'title' => E::ts('RelayState Allowlist'),
    'description' => E::ts('Newline- or comma-separated list of URL prefixes that are accepted as the post-login return target (RelayState). Defaults to this site\'s base URL. Anything not matching is redirected to /civicrm/home.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_SAML_AUTH_RELAYSTATE_ALLOWLIST',
  ],
];
