<?php

use CRM_SamlAuth_ExtensionUtil as E;

return [
  'saml_auth_enabled' => [
    'name' => 'saml_auth_enabled',
    'type' => 'Boolean',
    'default' => FALSE,
    'html_type' => 'checkbox',
    'title' => E::ts('Enable SAML Authentication'),
    'description' => E::ts('Enable SAML2-based Single Sign-On authentication'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_idp_entity_id' => [
    'name' => 'saml_auth_idp_entity_id',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('Identity Provider Entity ID'),
    'description' => E::ts('The Entity ID (Issuer) of your SAML Identity Provider'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_idp_sso_url' => [
    'name' => 'saml_auth_idp_sso_url',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('SSO URL'),
    'description' => E::ts('The Single Sign-On URL of your Identity Provider'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_idp_slo_url' => [
    'name' => 'saml_auth_idp_slo_url',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('SLO URL'),
    'description' => E::ts('The Single Logout URL of your Identity Provider (optional)'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_idp_x509_cert' => [
    'name' => 'saml_auth_idp_x509_cert',
    'type' => 'Text',
    'default' => '',
    'html_type' => 'textarea',
    'title' => E::ts('X.509 Certificate'),
    'description' => E::ts('The public X.509 certificate of your Identity Provider'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_sp_entity_id' => [
    'name' => 'saml_auth_sp_entity_id',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('Service Provider Entity ID'),
    'description' => E::ts('Your CiviCRM Entity ID (e.g., https://yoursite.org/civicrm)'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_enforce_sso' => [
    'name' => 'saml_auth_enforce_sso',
    'type' => 'Boolean',
    'default' => FALSE,
    'html_type' => 'checkbox',
    'title' => E::ts('Enforce SSO Only'),
    'description' => E::ts('Block traditional username/password login and require SAML SSO'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_bypass_key' => [
    'name' => 'saml_auth_bypass_key',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('Emergency Bypass Key'),
    'description' => E::ts('Secret key to bypass SSO enforcement (e.g., ?bypass=YOUR_KEY). Leave empty to disable bypass.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_debug' => [
    'name' => 'saml_auth_debug',
    'type' => 'Boolean',
    'default' => FALSE,
    'html_type' => 'checkbox',
    'title' => E::ts('Debug Mode'),
    'description' => E::ts('Enable detailed SAML debugging (logs to CiviCRM error log)'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_user_lookup_field' => [
    'name' => 'saml_auth_user_lookup_field',
    'type' => 'String',
    'default' => 'email',
    'html_type' => 'select',
    'title' => E::ts('User Lookup Field'),
    'description' => E::ts('Field to use for looking up existing users'),
    'is_domain' => 1,
    'is_contact' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_SamlAuth_Form_Settings::getUserLookupOptions',
    ],
  ],
  'saml_auth_enable_provisioning' => [
    'name' => 'saml_auth_enable_provisioning',
    'type' => 'Boolean',
    'default' => TRUE,
    'html_type' => 'checkbox',
    'title' => E::ts('Enable User Provisioning'),
    'description' => E::ts('Automatically create new users when they authenticate via SAML'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'saml_auth_role_attribute' => [
    'name' => 'saml_auth_role_attribute',
    'type' => 'String',
    'default' => '',
    'html_type' => 'text',
    'title' => E::ts('Role Attribute Name'),
    'description' => E::ts('SAML attribute name containing user roles (leave empty to disable role assignment). Roles from IdP must match CiviCRM role names exactly.'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
];
